# Generated by Django 2.1.5 on 2019-02-11 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('declined', 'Declined'), ('remaining', 'Remaining'), ('eliminated', 'Eliminated')], default='invited', max_length=10)),
                ('throw', models.CharField(blank=True, choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Roche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What the person has to do', max_length=300)),
                ('description', models.TextField(help_text='Conditions, stipulations, etc')),
                ('condition', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss')], default='loss', max_length=4)),
                ('condition_count', models.IntegerField(default=1, help_text='How many wins or losses?')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('complete', 'Complete'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired')], default='open', max_length=11)),
                ('fulfilled_at', models.DateTimeField(help_text='When was the roche fulfilled?')),
                ('proof', models.TextField(help_text='Describe what happened')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('performer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField()),
                ('roche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Roche')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='roche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Roche'),
        ),
        migrations.AddField(
            model_name='participant',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Round'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterOrderWithRespectTo(
            name='round',
            order_with_respect_to='roche',
        ),
        migrations.AlterOrderWithRespectTo(
            name='participant',
            order_with_respect_to='round',
        ),
    ]
