# Generated by Django 2.1.5 on 2019-02-11 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roche',
            name='fulfilled_at',
            field=models.DateField(blank=True, help_text='When was the roche fulfilled?'),
        ),
        migrations.AlterField(
            model_name='roche',
            name='performer',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='performer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roche',
            name='proof',
            field=models.TextField(blank=True, help_text='Describe what happened'),
        ),
    ]
