# Generated by Django 2.1.5 on 2019-02-11 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190211_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='throw',
            field=models.CharField(blank=True, choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='roche',
            name='fulfilled_at',
            field=models.DateField(blank=True, help_text='When was the roche fulfilled?', null=True),
        ),
        migrations.AlterField(
            model_name='roche',
            name='performer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roche',
            name='proof',
            field=models.TextField(blank=True, help_text='Describe what happened', null=True),
        ),
    ]
