# Generated by Django 2.1.5 on 2019-02-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190211_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
