# Generated by Django 2.1.5 on 2019-02-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190211_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roche',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='core.Profile'),
        ),
    ]
