# Generated by Django 2.1.5 on 2019-02-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190212_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='throw',
            field=models.CharField(blank=True, choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')], default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roche',
            name='proof',
            field=models.TextField(blank=True, help_text='Describe what happened'),
        ),
        migrations.AlterField(
            model_name='roche',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('complete', 'Complete'), ('fulfilled', 'Fulfilled')], default='open', max_length=11),
        ),
    ]
