# Generated by Django 2.1.5 on 2019-02-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190215_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='throw',
            field=models.CharField(blank=True, choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')], max_length=8, null=True),
        ),
    ]
