# Generated by Django 2.1.5 on 2019-02-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190216_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='outcome_count',
            field=models.IntegerField(blank=True, help_text='How many times the participant has won or lost', null=True),
        ),
    ]
