# Generated by Django 2.1.5 on 2019-02-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_participant_outcome_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='outcome_count',
            field=models.IntegerField(default=0, help_text='How many times the participant has won or lost'),
        ),
    ]
